services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "${PORT:-80}:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV
      - XDEBUG_MODE
      - XDEBUG_CONFIG
